### ISSUE TITLE
Stretch! Fish tracker

### ISSUE THREAD

**Issue by tsekeres** [tsekeres/ASSIGNMENT-Bear-Watcher#4]
- [ ] button for fish attempts on each card
- [ ] button for successful fish catches
- [ ] time stamped tallies for attempts and catches
- [ ] total catches tally/counter
